import { NextResponse } from 'next/server';

export async function GET() {
  const xml = `<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.dgaudiosound.com/</loc>
    <lastmod>2026-09-16</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/contacto</loc>
    <lastmod>2026-09-16</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/tienda</loc>
    <lastmod>2026-09-16</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/blog</loc>
    <lastmod>2026-09-16</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/residencial-premium</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/residencial-premium/cine-en-casa</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/residencial-premium/audio-distribuido</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/residencial-premium/audio-hi-fi</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/residencial-premium/family-room</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/residencial-premium/terrazas-y-jardin</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/residencial-premium/home-office</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/negocios-y-experiencias</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/negocios-y-experiencias/restaurantes</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/negocios-y-experiencias/bares-antros</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/negocios-y-experiencias/gimnasios</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/negocios-y-experiencias/cafeterias</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/negocios-y-experiencias/retail</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/negocios-y-experiencias/barberias</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/corporativo-e-institucional</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/corporativo-e-institucional/salas-de-juntas</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/corporativo-e-institucional/auditorios-corporativos</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/corporativo-e-institucional/gobierno</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/corporativo-e-institucional/oficinas-corporativas</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/corporativo-e-institucional/educacion</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/corporativo-e-institucional/hoteles</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/eventos-y-produccion</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/eventos-y-produccion/podcast</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/eventos-y-produccion/streamers</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/eventos-y-produccion/sonidos-dj</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/eventos-y-produccion/centros-de-culto</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/eventos-y-produccion/cine-independiente</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
  <url>
    <loc>https://www.dgaudiosound.com/eventos-y-produccion/musicos-vocalistas</loc>
    <lastmod>2026-09-19</lastmod>
  </url>
</urlset>`;

  return new NextResponse(xml, {
    headers: {
      'Content-Type': 'application/xml',
    },
  });
}
